// Pre-seeded Catalog Data for Rovingheights and Masobe Books

export const INITIAL_BOOKS = [
  {
    id: "bk-masobe-001",
    title: "Nearly All the Men in Lagos Are Mad",
    author: "Damilare Kuku",
    description: "A collection of twelve short stories focusing on relationships, love, and heartbreak in the bustling city of Lagos. Damilare Kuku delivers a humorous yet sharp critique of modern Nigerian romance.",
    coverImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=800",
    vendorPrice: 5000,
    retailPrice: 6500,
    sourceVendor: "masobe",
    sourceUrl: "https://masobebooks.com/shop/nearly-all-the-men-in-lagos-are-mad/",
    category: "Fiction",
    inStock: true,
    rating: 4.8,
    isbn: "978-978-984-211-7",
    pages: 240,
    publisher: "Masobe Books",
    featured: true,
    updatedAt: new Date().toISOString()
  },
  {
    id: "bk-roving-002",
    title: "Tomorrow I Become a Woman",
    author: "Aiwanose Odafen",
    description: "A poignant, heart-wrenching novel tracing the life of a young Nigerian woman navigating familial expectations, patriarchal oppression, and the search for autonomy during the complex 1970s and 80s.",
    coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=800",
    vendorPrice: 6200,
    retailPrice: 7800,
    sourceVendor: "rovingheights",
    sourceUrl: "https://rhbooks.com.ng/product/tomorrow-i-become-a-woman/",
    category: "African Literature",
    inStock: true,
    rating: 4.9,
    isbn: "978-147-228-868-4",
    pages: 368,
    publisher: "Scribner / Rovingheights",
    featured: true,
    updatedAt: new Date().toISOString()
  },
  {
    id: "bk-masobe-003",
    title: "Black Sunday",
    author: "Tola Rotimi Abraham",
    description: "Twin sisters Bibike and Ariyike navigate the sudden rupture of their middle-class life in Lagos after their mother loses her job in the turbulent 1990s. An unforgettable story of resilience.",
    coverImage: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&q=80&w=800",
    vendorPrice: 4800,
    retailPrice: 6200,
    sourceVendor: "masobe",
    sourceUrl: "https://masobebooks.com/shop/black-sunday/",
    category: "Fiction",
    inStock: true,
    rating: 4.7,
    isbn: "978-978-982-143-3",
    pages: 288,
    publisher: "Masobe Books",
    featured: false,
    updatedAt: new Date().toISOString()
  },
  {
    id: "bk-roving-004",
    title: "The Mechanics of Yenegoa",
    author: "Michael Afenfia",
    description: "An energetic, hilarious, and heartwarming story set in Yenagoa, following Ebi and the quirky ensemble around his mechanic workshop as they tackle money, brotherhood, and romance.",
    coverImage: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=800",
    vendorPrice: 4200,
    retailPrice: 5500,
    sourceVendor: "rovingheights",
    sourceUrl: "https://rhbooks.com.ng/product/the-mechanics-of-yenegoa/",
    category: "Fiction",
    inStock: true,
    rating: 4.6,
    isbn: "978-978-983-455-6",
    pages: 256,
    publisher: "Rovingheights Press",
    featured: false,
    updatedAt: new Date().toISOString()
  },
  {
    id: "bk-masobe-005",
    title: "Chronicles from the Land of the Happiest People on Earth",
    author: "Wole Soyinka",
    description: "Nobel laureate Wole Soyinka's monumental satirical masterpiece dissecting corruption, alliance, and spirituality in contemporary Nigeria with witty brilliance and unmatched prose.",
    coverImage: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&q=80&w=800",
    vendorPrice: 7500,
    retailPrice: 9500,
    sourceVendor: "masobe",
    sourceUrl: "https://masobebooks.com/shop/chronicles-from-the-land-of-the-happiest-people-on-earth/",
    category: "African Literature",
    inStock: true,
    rating: 4.9,
    isbn: "978-978-583-059-4",
    pages: 524,
    publisher: "Bookcraft / Masobe",
    featured: true,
    updatedAt: new Date().toISOString()
  },
  {
    id: "bk-roving-006",
    title: "Leaving the Tarmac: Buying a Bank in Africa",
    author: "Aigboje Aig-Imoukhuede",
    description: "An insider look into how two young Nigerian bankers took over Access Bank and transformed it from a minor financial institution into one of Africa's largest banking powerhouses.",
    coverImage: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=800",
    vendorPrice: 8500,
    retailPrice: 11000,
    sourceVendor: "rovingheights",
    sourceUrl: "https://rhbooks.com.ng/product/leaving-the-tarmac/",
    category: "Business",
    inStock: true,
    rating: 4.9,
    isbn: "978-191-377-601-5",
    pages: 312,
    publisher: "Rovingheights",
    featured: true,
    updatedAt: new Date().toISOString()
  },
  {
    id: "bk-masobe-007",
    title: "His Only Wife",
    author: "Peace Adzo Medie",
    description: "A witty, fast-paced Ghanaian drama about an arranged marriage, independence, and the sacrifices a young woman makes to define herself in a society built on tradition.",
    coverImage: "https://images.unsplash.com/photo-1532012164546-f432f2e3777f?auto=format&fit=crop&q=80&w=800",
    vendorPrice: 5200,
    retailPrice: 6800,
    sourceVendor: "masobe",
    sourceUrl: "https://masobebooks.com/shop/his-only-wife/",
    category: "Fiction",
    inStock: true,
    rating: 4.7,
    isbn: "978-978-984-762-4",
    pages: 288,
    publisher: "Masobe Books",
    featured: false,
    updatedAt: new Date().toISOString()
  },
  {
    id: "bk-roving-008",
    title: "The Sex Lives of African Women",
    author: "Nana Darkoa Sekyiamah",
    description: "A groundbreaking, intimate collection of stories celebrating the rich, complex, and diverse sexual lives of African women across the continent and the diaspora.",
    coverImage: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=800",
    vendorPrice: 7000,
    retailPrice: 9000,
    sourceVendor: "rovingheights",
    sourceUrl: "https://rhbooks.com.ng/product/the-sex-lives-of-african-women/",
    category: "Memoir",
    inStock: true,
    rating: 4.8,
    isbn: "978-0 dialogue-112-9",
    pages: 336,
    publisher: "Dialogue Books / Rovingheights",
    featured: false,
    updatedAt: new Date().toISOString()
  },
  {
    id: "bk-retala-009",
    title: "The Cost of Being a Girl",
    author: "Khadija Abdalla",
    description: "An evocative, penetrating exploration of girlhood, cultural autonomy, and resilience in contemporary Northern Nigeria. Distributed by Retala.",
    coverImage: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=800",
    vendorPrice: 4500,
    retailPrice: 5800,
    sourceVendor: "retala",
    sourceUrl: "https://retala.com.ng",
    category: "African Literature",
    inStock: true,
    rating: 4.8,
    isbn: "978-978-592-811-0",
    pages: 260,
    publisher: "Retala Distribution",
    featured: true,
    updatedAt: new Date().toISOString()
  }
];

export const INITIAL_ORDERS = [
  {
    id: "ORD-98234-NG",
    buyerId: "user_demo_01",
    buyerEmail: "tunde.adebayo@gmail.com",
    buyerName: "Tunde Adebayo",
    buyerPhone: "+2348031234567",
    items: [
      {
        bookId: "bk-masobe-001",
        title: "Nearly All the Men in Lagos Are Mad",
        quantity: 1,
        retailPrice: 6500,
        sourceVendor: "masobe",
        sourceUrl: "https://masobebooks.com/shop/nearly-all-the-men-in-lagos-are-mad/"
      }
    ],
    shippingAddress: "Plot 14 Admiralty Way, Lekki Phase 1",
    destinationState: "Lagos",
    shippingZoneTier: 1,
    bookSubtotal: 6500,
    shippingFee: 2000,
    totalPaid: 8500,
    paymentReference: "ps_live_89104820293",
    status: "in_transit",
    courierName: "GIG Logistics",
    trackingNumber: "GIG-89421190-NG",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString()
  },
  {
    id: "ORD-76129-NG",
    buyerId: "user_demo_02",
    buyerEmail: "amina.bello@yahoo.com",
    buyerName: "Amina Bello",
    buyerPhone: "+2348029876543",
    items: [
      {
        bookId: "bk-roving-006",
        title: "Leaving the Tarmac: Buying a Bank in Africa",
        quantity: 1,
        retailPrice: 11000,
        sourceVendor: "rovingheights",
        sourceUrl: "https://rhbooks.com.ng/product/leaving-the-tarmac/"
      }
    ],
    shippingAddress: "12 Shehu Shagari Way, Maitama",
    destinationState: "FCT (Abuja)",
    shippingZoneTier: 1,
    bookSubtotal: 11000,
    shippingFee: 2500,
    totalPaid: 13500,
    paymentReference: "ps_live_44910294811",
    status: "paid",
    courierName: "",
    trackingNumber: "",
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 4).toISOString()
  }
];
